name: Create Debug Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - run: ./gradlew test

  assemble:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - run: ./gradlew assembleChromaticDebug
      - run: ./gradlew assembleChromaticRelease
      - run: ./gradlew assembleMonochromaticDebug
      - run: ./gradlew assembleMonochromaticRelease

      - name: Sign APKs
        uses: Tlaster/android-sign@v1.2.2
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
        with:
          releaseDirectory: |
            app/build/outputs/apk/chromatic/debug/
            app/build/outputs/apk/chromatic/release/
            app/build/outputs/apk/monochromatic/debug/
            app/build/outputs/apk/monochromatic/release/
          output: app/build/outputs/signed/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: app-output
          path: app/build/outputs/

  checkIcons:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - run: sudo apt-get --quiet install --yes imagemagick
      - run: bash check_icons.sh